### ISSUE TITLE
MCU Menu should not be displayed in projects of other languages, as the CDT options do not appear.

### ISSUE THREAD

**Issue by carlosdelfino** [gnu-mcu-eclipse/eclipse-plugins#251] opened 2017-11-13 17:23 UTC
### Description

As I told you, my environment has several languages ​​installed and my Eclipse is a babel, Eclipse Oxygen seems to be much more stable in this simultaneous use, I am very satisfied and the GNU MCU Eclipse is working very well even with the Nordic nRF5x line .

I Use Eclipse for JavaScript and Web Developers for development with NativeScript a framework for Mobile multi platform Development and integration with bluetooth.

I noticed an interesting fact, the "MCU" configuration menu in the project properties is appearing in projects that are not connected to MCU (CDT Projects), this only happens with the GNU Eclipse MCU plugin.

For example if I create a JavaScript project, it should only appear the options related to the JavaScript compilation and assembly tools, but the MCU menu appears there too. Is this a setting that I can intervene with or just with a setting in the plugin code? 

### Steps to Reproduce

1. Use Eclipse Oxygen with JavaScript plugin (Eclipse for JavaScript and Web Developers)
2. Instal CDT and GNU MCU Eclipse Plugin
3. Create a JavaScript Project
4. Open de Project Property, you see MCU menu.

It should not appear, as the CDT options do not appear.

![MCU Menu in JavaScript Project](https://user-images.githubusercontent.com/369056/32738896-1268a52e-c87d-11e7-98f3-237b412d7530.png)

### Versions

* GNU MCU C/C++ ARM Cross Compiler	2.5.2.201711101735	
* Eclipse for JavaScript and Web Developers - Version: Oxygen.1a Release (4.7.1a) - Build id: 20171005-1200
* Java 1.8.0 151
* Windows 10

**Comment by ilg-ul** [comment] 2018-01-05 16:58
This should be a duplicate of #262, fixed.

**Closed by ilg-ul** 2018-01-05 16:58 UTC
Labels: bug
